swagger: '2.0'
info:
  title: My API
  version: '0.0.0'
basePath: /api/v1
securityDefinitions:
  basicAuth:
    type: basic
paths:
  /greet/{name}:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          in: path
          type: string
          required: true
        - name: nums
          in: query
          type: array
          collectionFormat: csv
          items:
            type: integer
          default: []
          maxItems: 3
      responses:
        200:
          description: Returns a greeting
          schema:
            type: string
  /secure:
    get:
      produces:
        - text/plain
      security:
        - basicAuth: []
      responses:
        200:
          description: Returns a secure message
          schema:
            type: string
